### ISSUE TITLE
Struggling to install in docker

### ISSUE THREAD

**Issue by baygaillardclasspass** [errbotio/err-backend-slackv3#64]
When I run this plugin locally, it works perfectly. However, when I attempt to push up a docker image (so that I can run my bot in the cloud), it's not working. 

Dockerfile: 

```
FROM python:3.8-slim as BUILD
WORKDIR /wheel
COPY . .
RUN apt update && apt install -y build-essential
RUN pip3 wheel --wheel-dir=/wheel \
    errbot errbot[slack] errbot[slack-sdk]

FROM python:3.8-slim
COPY --from=BUILD /wheel /wheel
RUN apt update && \
    apt install -y git && \
    cd /wheel && \
    pip3 -vv install --no-cache-dir --no-index --find-links /wheel \
    errbot errbot[slack] errbot[slack-sdk] && \
    pip3 install --extra-index-url https://pypi.python.org/simple boto3 slack_sdk mysql-connector-python && \
    rm -rf /wheel /var/lib/apt/lists/*

RUN useradd -m errbot
USER errbot
EXPOSE 3141 3142 80
VOLUME /home/errbot
WORKDIR /home/errbot
COPY --chown=errbot:errbot data/ ./data/
COPY --chown=errbot:errbot backend/ ./backend/
COPY --chown=errbot:errbot plugins/ ./plugins/
COPY --chown=errbot:errbot config.py ./

RUN cd backend/err-backend-slackv3 && pip3 install -r requirements.txt && pip3 install errbot[slack-sdk]

ENTRYPOINT [ "/usr/local/bin/errbot" ]
```

I have used a git submodule to include the backend under the `./backend` directory inside my git repository, where I have a config that was working fine when run locally, including fetching an api token from AWS SSM Parameter Store. Here is the error I am getting:

```
Successfully tagged platbot_platbot:latest
Recreating platbot_platbot_1 ... done
Attaching to platbot_platbot_1
platbot_1  | 2022-01-21 14:23:46,006 INFO     errbot.bootstrap          Found Storage plugin: Shelf.
platbot_1  | 2022-01-21 14:23:46,015 INFO     errbot.bootstrap          Found Backend plugin: SlackV3
platbot_1  | 2022-01-21 14:23:46,015 DEBUG    errbot.storage            Opening storage 'repomgr'
platbot_1  | 2022-01-21 14:23:46,015 DEBUG    errbot.storage.shelf      Open shelf storage ./data/repomgr.db
platbot_1  | 2022-01-21 14:23:46,039 ERROR    errbot.backends.slackv3   Could not start the SlackV3 backend
platbot_1  | Traceback (most recent call last):
platbot_1  |   File "backend/err-backend-slackv3/slackv3.py", line 37, in <module>
platbot_1  |     from slack_sdk.rtm.v2 import RTMClient
platbot_1  |   File "/usr/local/lib/python3.8/site-packages/slack_sdk/rtm/__init__.py", line 16, in <module>
platbot_1  |     import aiohttp
platbot_1  | ModuleNotFoundError: No module named 'aiohttp'
platbot_1  | 2022-01-21 14:23:46,040 CRITICAL errbot.backends.slackv3   You need to install python modules in order to use the Slack backend.
platbot_1  | You can do `pip install errbot[slack-sdk]` to install them.
```

**Comment by nzlosh** [comment]
Does fix it?
`RUN cd backend/err-backend-slackv3 && pip3 install -r requirements.txt && pip3 install errbot[slack-sdk] && pip install aiohttp`

**Comment by baygaillardclasspass** [comment]
No, I get the same error.

**Comment by nzlosh** [comment]
Don't do this, if you're planning on using the slackv3 backend
```RUN pip3 wheel --wheel-dir=/wheel \
    errbot errbot[slack] errbot[slack-sdk]```

**Comment by baygaillardclasspass** [comment]
Okay, I removed those but I still get the same error about `aiohttp` including telling me to install errbot[slack-sdk]...

**Comment by sijis** [comment]
@baygaillardclasspass This seems to work for me locally.
Note: the `config.py` isn't fully configured but its enough to show that the SlackV3 backend is loaded. Since you are using a predefined `config.py` from a repo, you may be able to ignore that RUN directive.

```
FROM python:3.8-slim
RUN useradd -m errbot
EXPOSE 3141 3142 80
WORKDIR /home/errbot
RUN apt update && apt install -y git gcc && \
    mkdir -p backend && \
    git clone https://github.com/errbotio/err-backend-slackv3.git backend/slackv3 && \
    pip3 install -r backend/slackv3/requirements.txt && \
    pip3 install errbot

USER errbot

# this could probably be ignored, as a config.py is being copied from the repo
RUN errbot --init && \
    echo '\nBOT_EXTRA_BACKEND_DIR="/home/errbot/backend"' >> config.py && \
    sed -i 's/Text/SlackV3/g' config.py

ENTRYPOINT [ "/usr/local/bin/errbot" ]
```

**Comment by msg4real** [comment]
Try https://github.com/msg4real/magbot-docker/blob/ef51b3ece8009f4e3e5354add887e3a38426f6ef/Dockerfile

**Comment by baygaillardclasspass** [comment]
I think I figured out what it's talking about: every time it replies at current, it says "@:" instead of "@baygaillard:" or whatever the triggering username was.
