### ISSUE TITLE
SlackApiError (user not found) on bot message, preventing errbot botcmd commands

### ISSUE THREAD

**Issue by in-op** [errbotio/err-backend-slackv3#67]
When another bot we have in our organization, [Standup Jack](https://standupjack.com/), posts messages, we get the following errors:

```
2022-05-25 13:39:57,151 ERROR    slack_sdk.socket_mode.builtin.client Failed to run a request listener: The request to the Slack API failed. (url: https://www.slack.com/api/users.info)
The server responded with: {'ok': False, 'error': 'user_not_found'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/client.py", line 151, in run_message_listeners
    listener(self, request)  # type: ignore
  File "/err/backend/err-backend-slackv3/slackv3.py", line 377, in _sm_generic_event_handler
    self._generic_wrapper(req.payload)
  File "/err/backend/err-backend-slackv3/slackv3.py", line 362, in _generic_wrapper
    return event_handler(self.slack_web, event)
  File "/err/backend/err-backend-slackv3/slackv3.py", line 534, in _handle_message
    msg.frm = SlackRoomBot(
  File "/err/backend/err-backend-slackv3/_slack/room.py", line 334, in __init__
    super().__init__(webclient, bot_id, bot_username)
  File "/err/backend/err-backend-slackv3/_slack/room.py", line 308, in __init__
    super().__init__(webclient, userid=bot_id)
  File "/err/backend/err-backend-slackv3/_slack/person.py", line 50, in __init__
    self._cache_user_info()
  File "/err/backend/err-backend-slackv3/_slack/person.py", line 88, in _cache_user_info
    res = self._webclient.users_info(user=self._userid)
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/web/client.py", line 4192, in users_info
    return self.api_call("users.info", http_verb="GET", params=kwargs)
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/web/base_client.py", line 145, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/web/base_client.py", line 182, in _sync_send
    return self._urllib_api_call(
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/web/base_client.py", line 316, in _urllib_api_call
    return SlackResponse(
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/web/slack_response.py", line 205, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/users.info)
The server responded with: {'ok': False, 'error': 'user_not_found'}
```

Jack posts _as_ other people - this may be relevant. It looks like slackv3 tries to look up a user by bot ID and fails.

This is an issue because any errbot command triggers from these bot messages fail.

**Comment by duhow** [comment]
To understand the problem:
You want the "bot messages" that are sent in behalf of other users, to be accepted by Errbot?

**Comment by in-op** [comment]
@duhow yes. We did not have this issue using the default slack backend (we upgraded to slackv3 as RTM Slack apps are EOL this year). This was the only regression in our chatbot.

**Comment by nzlosh** [comment]
Can you provide a sanitised copy of the slack events for a user issuing a bot command and Jack bot issuing a bot command on behalf of a user please?  An example of the events I'm talking about are shown below when running with log level set to `DEBUG`.

```
09:39:09 DEBUG    slack_sdk.rtm_v2          on_message invoked: (message: {"type":"message","user":"UL6DDE8BS","channel":"CL8HNNTFY","text":"!help","blocks":[{"type":"rich_text","block_id":"==Djr","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"!help"}]}]}],"client_msg_id":"1fade66a-3df1-4294-986d-58d4b310acf0","team":"TL5UZGMU4","source_team":"TL5UZGMU4","user_team":"TL5UZGMU4","suppress_notification":false,"event_ts":"1654155549.068859","ts":"1654155549.068859"})
```

**Comment by brickrakowsky** [comment]
Howdy, we've run into the same issue with the self._cache_user_info() function in SlackPerson. We use Slack workflows to interact with errbot and requests from these have a bot ID not a user ID. 

I had a play round with it and it can be resolved if you do a call to the bot.info endpoint beforehand. This endpoint gives you an equivalent user ID for the bot ID of the bot/workflow

**Comment by nzlosh** [comment]
Nice find @brickrakowsky, would you be able to put together a PR with the fix?

**Comment by jcfrt** [comment]
Thanks @brickrakowsky for the message, this actually clears things up. I'm currently affected by this bug and was really wondering why I get flooded by error messages generated by bot uids.

**Comment by in-op** [comment]
I believe the above MR fixed the issue, we don't see that error anymore. Closing.

**Comment by nzlosh** [comment]
Thanks for confirming :+1:
