### ISSUE TITLE
Exception while using add_reaction in release v0.1.1

### ISSUE THREAD

**Issue by rohopt** [errbotio/err-backend-slackv3#77]
Hello, 

I had cloned the latest release v0.1.1 and encountered the following bug while using add_reaction() method:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/errbot/core.py", line 574, in _execute_and_send
    reply = method(msg, match) if match else method(msg, args)
  File "/opt/errbot/extra_plugins/err-shellexec/shellexec.py", line 217, in new_method
    self._bot.add_reaction(msg,workingEmoji)
  File "/opt/errbot/backend/err-backend-slackv3/slackv3.py", line 998, in add_reaction
    return self._react("reactions.add", msg, reaction)
  File "/opt/errbot/backend/err-backend-slackv3/slackv3.py", line 1019, in _react
    self.api_call(
  File "/opt/errbot/backend/err-backend-slackv3/slackv3.py", line 120, in api_call
    response = self.slack_web.api_call(method, **data)
TypeError: api_call() got an unexpected keyword argument 'channel'
```

Note: The above exception is not seen when I use the code from main branch and things work as expected.

Please let me know if any further information is required.

**Comment by nzlosh** [comment]
Thank you for reporting this issue.  A patch has been merged to master for issue and will be released under `0.2.0`.
